// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCobP-WHbS2G-kziRDQhFBNrXxZB3fPhdU',
    appId: '1:860409466297:android:0bb9dace6170321e63fa68',
    messagingSenderId: '860409466297',
    projectId: 'pills-bd823',
    databaseURL: 'https://pills-bd823-default-rtdb.firebaseio.com',
    storageBucket: 'pills-bd823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_68tnMj5FxTLSAFYT4RQHlQ-9AqPuN0',
    appId: '1:860409466297:ios:951f30ef43af5b6763fa68',
    messagingSenderId: '860409466297',
    projectId: 'pills-bd823',
    databaseURL: 'https://pills-bd823-default-rtdb.firebaseio.com',
    storageBucket: 'pills-bd823.appspot.com',
    androidClientId: '860409466297-agmv7tvdgm3h5v5k22vnd825f7m0s65m.apps.googleusercontent.com',
    iosClientId: '860409466297-2093uv533mj2rd9dk602ob2mobuoavgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pills',
  );
}
